name: CI/CD Pipeline  

on:  
  push:  
    branches:  
      - main  
  pull_request:  

jobs:  
  build-test-deploy:  
    runs-on: ubuntu-latest  

    steps:  
      # Step 1: Checkout the repository  
      - name: Checkout Code  
        uses: actions/checkout@v3  

      # Step 2: Set up Python  
      - name: Set up Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: 3.9  

      # Step 3: Install dependencies  
      - name: Install Dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install -r requirements.txt  

      # Step 4: Run tests  
      - name: Run Tests  
        run: |  
          pytest  

      # Step 5: Set up Docker  
      - name: Log in to Docker Hub  
        uses: docker/login-action@v2  
        with:  
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build and Push Docker Image  
        run: |  
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }} .  
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}  

      # Optional Step: Deploy to a server  
      - name: Deploy to Server  
        run: |  
          ssh user@your-server-ip "docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }} && docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}"  
