# Use an official Python runtime as the base image  
FROM python:3.9-slim  
  
# Set the working directory  
WORKDIR /app  
  
# Copy the requirements and app files  
COPY requirements.txt .  
RUN pip install -r requirements.txt  
COPY . .  
  
# Expose the default Flask port  
EXPOSE 5000  
  
# Define the entry point  
CMD ["flask", "run", "--host=0.0.0.0"]  
